# Generated by Django 4.0.4 on 2022-05-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=80)),
                ('add_on_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('complete', 'Completed'), ('pending', 'Pending')], default='Pending', max_length=10)),
                ('user_id', models.CharField(max_length=500)),
            ],
        ),
    ]
