# Generated by Django 4.0.4 on 2022-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_home', '0002_user_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task',
            name='add_on_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='deadline_date',
            field=models.DateField(),
        ),
    ]
