# Generated by Django 4.0.4 on 2022-05-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_home', '0008_delete_task_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
